# Generated by Django 3.1.3 on 2020-11-12 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chip',
            fields=[
                ('idnumero', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('ativo', models.CharField(max_length=1)),
                ('disponivel', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'chip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('idcidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(blank=True, max_length=60, null=True)),
                ('bairro', models.CharField(blank=True, max_length=30, null=True)),
                ('datacadastro', models.DateField(blank=True, null=True)),
                ('cancelado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('idregiao', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'cobertura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('uf', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('ddd', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('referencia', models.DateField(primary_key=True, serialize=False)),
                ('valor_plano', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tot_min_int', models.IntegerField()),
                ('tot_min_ext', models.IntegerField()),
                ('tx_min_exced', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tx_roaming', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pago', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'fatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operadora',
            fields=[
                ('idoperadora', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'operadora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('idplano', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
                ('fminin', models.IntegerField()),
                ('fminout', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'db_table': 'plano',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('idtarifa', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'tarifa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('idnumero', models.OneToOneField(db_column='idnumero', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ifmobileDatabase.chip')),
                ('datainicio', models.DateField()),
                ('datatermino', models.DateField()),
            ],
            options={
                'db_table': 'auditoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteChip',
            fields=[
                ('idnumero', models.OneToOneField(db_column='idnumero', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ifmobileDatabase.chip')),
            ],
            options={
                'db_table': 'cliente_chip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanoTarifa',
            fields=[
                ('idplano', models.OneToOneField(db_column='idplano', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ifmobileDatabase.plano')),
            ],
            options={
                'db_table': 'plano_tarifa',
                'managed': False,
            },
        ),
    ]
