# Generated by Django 3.1.3 on 2020-11-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifmobileDatabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ligacao',
            fields=[
                ('datalig', models.DateTimeField(primary_key=True, serialize=False)),
                ('duracao', models.DurationField()),
            ],
            options={
                'db_table': 'ligacao',
                'managed': False,
            },
        ),
    ]
